### ISSUE TITLE
The link is invalid

### ISSUE THREAD

**Issue by zed-2018** [Oldpan/faceswap-pytorch#2]
Hello, this link is invalid.
https://space.oldpan.me/f/cccac1136338407797cb/?dl=1

**Comment by Oldpan** [comment]
You can use BaiduYun: [Here](https://pan.baidu.com/s/1BlHvPmD50MAJmAbn_VTgGQ)   pw : tt66

**Comment by zed-2018** [comment]
Thank you！

**Comment by tasinislam21** [comment]
Can you upload it to google drive? They are asking me to create an account and download software.
